version: '3.8'
services:
  db:
    image: postgres:14.2
    container_name: happy-pig-database
    restart: always
    environment:
      - POSTGRES_DB=happy_pig
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=fakepassword123
      - POSTGRES_PORT=5432
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  app:
    image: alkruhglov777/happy-pig-core:0.0.0.1
    container_name: happy-pig-app
    ports:
      - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/happy_pig
    restart: always
    links:
      - db

volumes:
  db:
    driver: local
