import {
  ArrowDownOutlined,
  ArrowLeftOutlined,
  ArrowUpOutlined,
  BankOutlined,
  BookOutlined,
  CalendarOutlined,
  CheckOutlined,
  CheckCircleOutlined,
  CloseOutlined,
  CloseCircleOutlined,
  DollarOutlined,
  DeleteOutlined,
  EditOutlined,
  FilterOutlined,
  PlusOutlined,
  UserOutlined,
  LockOutlined,
  MailOutlined,
  LogoutOutlined,
  TransactionOutlined,
  MinusCircleOutlined,
  InfoCircleOutlined,
  LinkOutlined,
  TagOutlined,
  TagsOutlined,
  SendOutlined
} from '@ant-design/icons';

export {
  ArrowLeftOutlined as ArrowLeftIcon,
  BookOutlined as BookIcon,
  DeleteOutlined as DeleteIcon,
  FilterOutlined as FilterIcon,
  PlusOutlined as AddIcon,
  EditOutlined as EditIcon,
  UserOutlined as AvatarIcon,
  CheckOutlined as CheckIcon,
  CheckCircleOutlined as CheckCircleIcon,
  CloseOutlined as CloseIcon,
  CloseCircleOutlined as CloseCircleIcon,
  BankOutlined as BankIcon,
  DollarOutlined as DollarIcon,
  LockOutlined as LockIcon,
  MailOutlined as MailIcon,
  LogoutOutlined as LogoutIcon,
  ArrowUpOutlined as ArrowUpIcon,
  ArrowDownOutlined as ArrowDownIcon,
  TransactionOutlined as TransactionIcon,
  MinusCircleOutlined as MinusCircleIcon,
  InfoCircleOutlined as InfoIcon,
  LinkOutlined as LinkIcon,
  TagOutlined as TagIcon,
  TagsOutlined as TagsIcon,
  CalendarOutlined as CalendarIcon,
  SendOutlined as SendIcon
};
