import {
  ArrowLeftOutlined,
  DeleteOutlined,
  PlusOutlined,
  EditOutlined,
  UserOutlined,
  CheckOutlined,
  CloseOutlined,
  BankOutlined,
  DollarOutlined,
  LockOutlined,
  MailOutlined,
  LogoutOutlined,
  ArrowUpOutlined,
  ArrowDownOutlined,
  TransactionOutlined,
  MinusCircleOutlined,
  InfoCircleOutlined,
  LinkOutlined
} from '@ant-design/icons';

export {
  ArrowLeftOutlined as ArrowLeftIcon,
  DeleteOutlined as DeleteIcon,
  PlusOutlined as AddIcon,
  EditOutlined as EditIcon,
  UserOutlined as AvatarIcon,
  CheckOutlined as CheckIcon,
  CloseOutlined as CloseIcon,
  BankOutlined as BankIcon,
  DollarOutlined as DollarIcon,
  LockOutlined as LockIcon,
  MailOutlined as MailIcon,
  LogoutOutlined as LogoutIcon,
  ArrowUpOutlined as ArrowUpIcon,
  ArrowDownOutlined as ArrowDownIcon,
  TransactionOutlined as TransactionIcon,
  MinusCircleOutlined as MinusCircleIcon,
  InfoCircleOutlined as InfoIcon,
  LinkOutlined as LinkIcon
};
